### ISSUE TITLE
title should not be tied to comment id

### ISSUE THREAD

**Issue by Aghassi** [intuit/commently#31]
## 🐛 Bug Report

The title passed in is also set as the comment unique ID in the GitHub comment, which is incorrect. They should be two separate things.

https://github.com/intuit/commently/blob/6ecfe4fce2e0a06b9b7fbf5e57903d70b9b0cee4/packages/core/core.ts#L64

## To Reproduce

Initialize with a title and notice that the title that overrides the default `commently` is the whole title and not a unique id.

## Expected behavior

The hidden unique id should be separate from the comment title. This requires just a separate arg in the constructor to be defined.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v0.1.0 :rocket:
