### ISSUE TITLE
Commitlint support 

### ISSUE THREAD

**Issue by christyjacob4** [intuit/commently#474]
## 🚀 Feature Proposal

Hi I'd like to add commit lint support to the repo and add a husky pre-commit hook for the same
https://github.com/conventional-changelog/commitlint 

## Motivation
This would ensure that contributors ensure commit message sanity 

## Example

![Screenshot 2020-10-01 at 9 10 21 PM](https://user-images.githubusercontent.com/20852629/94831588-874c6380-042a-11eb-9147-09862ba338a8.png)

**Comment by Aghassi** [comment]
Closed by #475
